#!/usr/bin/sh

function fcd() { 
    search_result=$(find "$@" -path "*/node_modules" -prune \
                             -o -path "./proc/*" -prune \
                             -o -path "/proc/*" -prune \
                             -o -type d -print 2>/dev/null | fzf --tiebreak=begin)
    
    if [[ -n "$search_result" ]]; then
        cd "$search_result" 
    fi
}
