#!/usr/bin/sh

function fcd() { 
    search_result=$(find $@ -path "*/node_modules" -prune -path "./proc/*" -prune -path "/proc/*" -prune -o -type d | sort -u | fzf)
    
    if [[ ! -z $search_result ]] then
        cd $search_result 
    fi
};
