#!/usr/bin/zsh

function ffcd()
{
    search_result=$(find $@ -path "*/node_modules" -prune -path "./proc/*" -prune -path "/proc/*" -prune -o -type d | fzf)

    if [[ -z $search_result ]] then
	return
    fi

    directory_name=$(dirname $search_result)

    if [[ ! -z $directory_name ]] then
        cd $directory_name
    fi
}
