#!/usr/bin/zsh

function tmux-neww-def()
{
    if [[ -z $TMUX ]]; then
        echo "Not in a TMUX session"
        return
    fi

    search_result=$(find $@ -path "./proc/*" -prune -o -path "/proc/*" -prune -o -type d | fzf)

    if [[ -z $search_result ]]; then
        return
    fi

    tmux new-window -c $search_result
}
